### ISSUE TITLE
Wrong number of CC for osm-eur-karlsruhe.gr

### ISSUE THREAD

**Issue by sgpyc** [groute/ppopp17-artifact#1]
Hi, I followed the build instruction, and try to run CC on the osm-eur graph, and the program says there're 6693424 disconnected components in the europe road network, which is highly impossible. The provided bfs result (dataset/OSM-eur-k/bfs-osm-eur-karlsruhe.gr.txt) does not list any vertex with INF label; I also run Gunrock's CC primitive on the same graph, which reports 1 single component by both the CPU and the GPU code; Gunrock's BFS from vertex 0 touches the whole graph, and produces identical results as the provided bfs result.

Can you verify the correctness of the CC implementation?

```
sgpyc@mario:~/Projects/Groute/ppopp17-artifact/code/groute/build$ ./cc -num_gpus 4 --startwith 4 -graphfile /data/gunrock_dataset/huge/osm-eur/osm-eur.Galois_gr
Running CC with 4 GPUs, starting with 4 GPUs
Testing with 4 GPUs
--------------------


Loading graph /data/gunrock_dataset/huge/osm-eur/osm-eur.Galois_gr (1)
/data/gunrock_dataset/huge/osm-eur/osm-eur.Galois_gr has 173789185 nodes and 347997111 edges
read 347997111 edges
read data for 347997111 edges

----- Running CC Async -----


CC (Async): 136.520000 ms. <filter>


Components: 6693424

Overall: Test passed
```

**Comment by sgpyc** [comment]
The single GPU implementation also reports 6.7M components.

```
sgpyc@mario:~/Projects/Groute/ppopp17-artifact/code/groute/build$ ./cc -num_gpus 1 --startwith 1 -graphfile ../../../dataset/OSM-eur-k/osm-eur-karlsruhe.gr
Testing with 1 GPUs
--------------------


Loading graph ../../../dataset/OSM-eur-k/osm-eur-karlsruhe.gr (1)
../../../dataset/OSM-eur-k/osm-eur-karlsruhe.gr has 173789185 nodes and 347997111 edges
read 347997111 edges
read data for 347997111 edges

----- Running CC Async -----


CC (Async): 188.015000 ms. <filter>


Components: 6693424

Overall: Test passed
```

**Comment by tbennun** [comment]
Hi,
The issue seems to be the result of command line flags. The default flags treat the graph as undirected, removing duplicate edges. In OSM-europe, the graph is directed, so edges appear once and are removed. To tread the graph as directed (i.e., having no duplicate edges) the flag `--undirected=false` should be added, as is performed in the artifact runner script.

Results:

```
./cc -num_gpus 1 -startwith 1 -undirected=false -graphfile ../../../dataset/OSM-eur-k/osm-eur-karlsruhe.gr 
Testing with 1 GPUs
--------------------


Loading graph ../../../dataset/OSM-eur-k/osm-eur-karlsruhe.gr (1)
../../../dataset/OSM-eur-k/osm-eur-karlsruhe.gr has 173789185 nodes and 347997111 edges
read 347997111 edges
read data for 347997111 edges

----- Running CC Async -----


CC (Async): 220.031000 ms. <filter>


Components: 1

Overall: Test passed
```

**Comment by tbennun** [comment]
One more note, this flag should probably not be true by default, and it will be corrected in the next commit.

**Comment by sgpyc** [comment]
Yup, adding `-undirected=false` will output 1 component.

But I don't understand the following:
1. Soman's algorithm does not consider the direction of the edges. In Fig. 3 ("Algorithm for Connected Components") of the paper, there is no difference in treating the source or the destination vertex of an edge.

2. If the directed version of a graph is connected, the undirected version of the same graph should also be connected.

Am I missing anything here?

**Comment by tbennun** [comment]
The connected components algorithm is intended for undirected graphs. 

The `-undirected` flag simply removes duplicate edges while the graph is being read from the file in a very straightforward way. IIRC, it only allows edges that point forward in node indices, so (1,2) is allowed but (2,1) is filtered. In any case, this should not be the default command line flag.

Thanks for reporting this.

**Comment by sgpyc** [comment]
Is `-undirected` on by default for other primitives?

**Comment by tbennun** [comment]
It is a CC-specific flag. Used here:
https://github.com/groute/groute/blob/master/samples/cc/cc_load.h#L112
